x-airflow-common:
  &airflow-common
  image: ${AIRFLOW_IMAGE_NAME:-apache/airflow:3.2.0}
  env_file:
    - .env.docker
  environment:
    &airflow-common-env
    AIRFLOW__CORE__EXECUTOR: CeleryExecutor
    AIRFLOW__CORE__AUTH_MANAGER: airflow.providers.fab.auth_manager.fab_auth_manager.FabAuthManager
    AIRFLOW__CELERY__BROKER_URL: redis://:@redis:6379/0
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true' #TODO: change to false after testing
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    AIRFLOW__CORE__EXECUTION_API_SERVER_URL: 'http://airflow-apiserver:8080/execution/'
    AIRFLOW__SCHEDULER__ENABLE_HEALTH_CHECK: 'true'
    PYTHONPATH: /opt/workspace
    AWS_DEFAULT_REGION: ap-southeast-1
  volumes:
    - ../../src/orchestration/airflow/dags:/opt/airflow/dags
    - ../../logs:/opt/airflow/logs
    - ../../:/opt/workspace
  user: "${AIRFLOW_UID:-50000}:0"
  depends_on:
    &airflow-common-depends-on
    redis:
      condition: service_healthy
    postgres:
      condition: service_healthy

services:
  postgres:
    image: postgres:16
    env_file:
      - .env.docker
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER:-airflow}"]
      interval: 10s
      retries: 5
      start_period: 5s
    restart: always

  redis:
    image: redis:7.2-bookworm
    expose:
      - 6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 30s
      retries: 50
      start_period: 30s
    restart: always

  airflow-apiserver:
    <<: *airflow-common
    command: api-server
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/api/v2/monitor/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: always
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: service_completed_successfully

  airflow-scheduler:
    <<: *airflow-common
    command: scheduler
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8974/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: always
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: service_completed_successfully

  airflow-dag-processor:
    <<: *airflow-common
    command: dag-processor
    healthcheck:
      test: ["CMD-SHELL", 'airflow jobs check --job-type DagProcessorJob --hostname "$${HOSTNAME}"']
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: always
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: service_completed_successfully

  airflow-worker:
    <<: *airflow-common
    build:
      context: .
      dockerfile: Dockerfile.airflow
    command: celery worker
    healthcheck:
      test: ["CMD-SHELL", 'celery --app airflow.providers.celery.executors.celery_executor.app inspect ping -d "celery@$${HOSTNAME}"']
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    environment:
      <<: *airflow-common-env
      DUMB_INIT_SETSID: "0"
    volumes:
      - ../../src/orchestration/airflow/dags:/opt/airflow/dags
      - ../../logs:/opt/airflow/logs
      - ../../:/opt/workspace
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    depends_on:
      <<: *airflow-common-depends-on
      airflow-apiserver:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully

  airflow-triggerer:
    <<: *airflow-common
    command: triggerer
    healthcheck:
      test: ["CMD-SHELL", 'airflow jobs check --job-type TriggererJob --hostname "$${HOSTNAME}"']
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: always
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: service_completed_successfully

  airflow-init:
    <<: *airflow-common
    entrypoint: ["/bin/bash", "/opt/airflow/scripts/build_docker.sh"]
    volumes:
      - ../../src/orchestration/airflow/dags:/opt/airflow/dags
      - ../../logs:/opt/airflow/logs
      - ../../scripts/build_docker.sh:/opt/airflow/scripts/build_docker.sh
    environment:
      <<: *airflow-common-env
    user: "0:0"

  airflow-cli:
    <<: *airflow-common
    profiles:
      - debug
    environment:
      <<: *airflow-common-env
      CONNECTION_CHECK_MAX_COUNT: "0"
    command: bash -c airflow
    depends_on:
      <<: *airflow-common-depends-on

  flower:
    <<: *airflow-common
    command: celery flower
    profiles:
      - flower
    ports:
      - "5555:5555"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:5555/"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: always
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: service_completed_successfully

  spark-master:
    image: apache/spark:3.5.0
    container_name: spark-master
    command: >
      /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
    ports:
      - "8090:8080"
      - "7077:7077"
    volumes:
      - ../../:/opt/workspace
      - ../../data/raw:/opt/dataset

  spark-worker-1:
    build:
      context: .
      dockerfile: Dockerfile.pipeline
    container_name: spark-worker-1
    command: >
      /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    environment:
      - SPARK_WORKER_CORES=3
      - SPARK_WORKER_MEMORY=4G
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    volumes:
      - ../../:/opt/workspace
      - ../../data/raw:/opt/dataset
      - ~/.aws:/root/.aws:ro
    mem_limit: 4g
    cpus: 3

  spark-worker-2:
    build:
      context: .
      dockerfile: Dockerfile.pipeline
    container_name: spark-worker-2
    command: >
      /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    environment:
      - SPARK_WORKER_CORES=3
      - SPARK_WORKER_MEMORY=4G
    depends_on:
      - spark-master
    ports:
      - "8082:8081"
    volumes:
      - ../../:/opt/workspace
      - ../../data/raw:/opt/dataset
      - ~/.aws:/root/.aws:ro
    mem_limit: 4g
    cpus: 3

  spark-submit:
    build:
      context: .
      dockerfile: Dockerfile.pipeline
    container_name: spark-submit
    user: root
    depends_on:
      - spark-master
    env_file:
      - .env.docker
    environment:
      - PYTHONPATH=/opt/workspace
      - ENV=prod
      - AWS_DEFAULT_REGION=ap-southeast-1
    volumes:
      - ../../:/opt/workspace
      - ../../data/raw:/opt/dataset
    command: ["bash"]

  superset-db:
    image: postgres:17
    container_name: superset_db
    env_file:
      - ./superset/.env
    volumes:
      - superset-db-volume:/var/lib/postgresql/data
      - ./superset/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "superset"]
      interval: 10s
      retries: 5
      start_period: 5s
    restart: unless-stopped

  superset-redis:
    image: redis:7
    container_name: superset_cache
    restart: unless-stopped
    volumes:
      - superset-redis-volume:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  superset-init:
    image: apache/superset:latest
    container_name: superset_init
    command: ["/app/docker/docker-init.sh"]
    env_file:
      - ./superset/.env
      - .env.docker
    environment:
      DATABASE_HOST: superset-db
      REDIS_HOST: superset-redis
      EXAMPLES_HOST: superset-db
      AWS_DEFAULT_REGION: ap-southeast-1
    user: "root"
    depends_on:
      superset-db:
        condition: service_healthy
      superset-redis:
        condition: service_healthy
    volumes:
      - ./superset:/app/docker
      - superset-home-volume:/app/superset_home
    restart: "no"

  superset:
    image: apache/superset:latest
    container_name: superset_app
    command: ["/app/docker/docker-bootstrap.sh", "app-gunicorn"]
    env_file:
      - ./superset/.env
      - .env.docker
    environment:
      DATABASE_HOST: superset-db
      REDIS_HOST: superset-redis
      EXAMPLES_HOST: superset-db
      AWS_DEFAULT_REGION: ap-southeast-1
    user: "root"
    restart: unless-stopped
    ports:
      - "8088:8088"
    depends_on:
      superset-init:
        condition: service_completed_successfully
    volumes:
      - ./superset:/app/docker
      - superset-home-volume:/app/superset_home

  superset-worker:
    image: apache/superset:latest
    container_name: superset_worker
    command: ["/app/docker/docker-bootstrap.sh", "worker"]
    env_file:
      - ./superset/.env
      - .env.docker
    environment:
      DATABASE_HOST: superset-db
      REDIS_HOST: superset-redis
      EXAMPLES_HOST: superset-db
      AWS_DEFAULT_REGION: ap-southeast-1
    user: "root"
    restart: unless-stopped
    depends_on:
      superset-init:
        condition: service_completed_successfully
    volumes:
      - ./superset:/app/docker
      - superset-home-volume:/app/superset_home
    healthcheck:
      test: ["CMD-SHELL", "celery -A superset.tasks.celery_app:app inspect ping -d celery@$$HOSTNAME"]

  superset-worker-beat:
    image: apache/superset:latest
    container_name: superset_worker_beat
    command: ["/app/docker/docker-bootstrap.sh", "beat"]
    env_file:
      - ./superset/.env
      - .env.docker
    environment:
      DATABASE_HOST: superset-db
      REDIS_HOST: superset-redis
      EXAMPLES_HOST: superset-db
      AWS_DEFAULT_REGION: ap-southeast-1
    user: "root"
    restart: unless-stopped
    depends_on:
      superset-init:
        condition: service_completed_successfully
    volumes:
      - ./superset:/app/docker
      - superset-home-volume:/app/superset_home
    healthcheck:
      disable: true

volumes:
  postgres-db-volume:
  superset-db-volume:
  superset-redis-volume:
  superset-home-volume:
